### ISSUE TITLE
Logo Design Proposal

### ISSUE THREAD

**Issue by Tobaloidee** [tattn/SwipeTransition#10]
Greetings Sir @tattn , I am a graphics designer and i passed by your nice project and i noticed it doesn't have a logo yet. I want to propose a logo design for it as a gift for free, if you will give me permission i will start immediately and show you here. Thanks and best regards! - tobaloidee

**Comment by tattn** [comment]
Oh my god! I'm so happy :-))))))
Thank you for your proposal! I really appreciate it. 
I am looking forward to it 😄

**Comment by Tobaloidee** [comment]
You are welcome Sir..ill work on it and show you here when i get home Sir..

**Comment by tattn** [comment]
Looks great! I like the red color version. 😄 

Both logotypes are good.
In README, I'd like to use the logo with text on the right of favicon.
In a small space, I'd like to use the logo with the text on the bottom of favicon.

Could you create a PR?
Please put `.png` and `.svg` on `docs/assets`, and use the `.png` image for the README.

**Comment by Tobaloidee** [comment]
here's the PR  #11 where i uploaded the SVG & PNG files and updated the Readme. Thanks Sir!

**Comment by tattn** [comment]
I merged #11 
Thank you so much 👍
