### ISSUE TITLE
COCOAPOD: Invalid redeclaration of 'InteractiveTransition'

### ISSUE THREAD

**Issue by BluePick** [tattn/SwipeTransition#12]
![screen shot 2018-06-22 at 11 10 01 am](https://user-images.githubusercontent.com/8054759/41759597-e1efd3de-760c-11e8-8885-38404516795e.png)

Please fix the issue

**Comment by tattn** [comment]
Hi, 
I tried it, but  it didn't reproduce...

![image](https://user-images.githubusercontent.com/8188636/44728299-0f0e6800-ab17-11e8-83be-10fe0358f233.png)

I think it is a bug of cocoapods.
Please try the following steps:
1. remove `pod "SwipeTransition"` in Podfile
2. run `pod install`
3. add `pod "SwipeTransition"` in Podfile
4. run `pod install`

if you reproduce it again, please send the issue again
