### ISSUE TITLE
formSheet crash

### ISSUE THREAD

**Issue by Silent404** [tattn/SwipeTransition#14]
`let viewController = ViewController()
viewController.modalPresentationStyle = .formSheet
        viewController.popoverPresentationController?.sourceView = view
        present(viewController, animated: true, completion: nil)`

In case of screen transition, swipe the crash of the navigation bar

**Comment by tattn** [comment]
Sorry, `.formSheet` style is not support yet...
Please disable the swipe gesture in the viewcontroller.

Please wait for the future version or send pull request :D
