### ISSUE TITLE
Weird behavior since August update

### ISSUE THREAD

**Issue by A1exandre** [tattn/SwipeTransition#15]
Hi & thanks for the good work I've been using for some time :)

Just updated my cocoapods and now the swipe to go back move does not really work anymore:
- slow, reactive, swipe does not work (ie controlling the animation with your finger)
- only thing that work is that if i do a quick swipe at the center of the screen, I still go back. But I cannot control the animation with my finger
This results in a pretty bad user experience.

Any idea how to fix this?

Thanks

Some details on my setup:
-  My project is written is swift
- I use SwipeTransitionAutoSwipeBack in my linked frameworks to setup everything automatically
- The view from which I need to swipe back contains a WKWebBrowser

**Comment by shmakovigor** [comment]
The same problem if UIViewController contains any UIScrollView subclass. Interactive pop transition is broken, only quick swipe at the center of the screen works. Any ideas how to fix that?

**Comment by tattn** [comment]
Thanks for good issues!
I fixed the problem about scroll views.
Please try `0.3.2` 👍

**Comment by shmakovigor** [comment]
Great, thanks! Everything works as expected now 👌🏽
