### ISSUE TITLE
Objective-c support stoped work after swift 4.2

### ISSUE THREAD

**Issue by CavalcanteLeo** [tattn/SwipeTransition#18]
I cant access the property `isEnabled` anymore

before i had to use `#import <SwipeTransition/SwipeTransition-Swift.h>`, but not, xcode cant find it, instead i have access to  `#import <SwipeTransition/SwipeTransition.h>`

![captura de tela 2018-09-20 as 13 40 11](https://user-images.githubusercontent.com/1735944/45833306-c80d3000-bcda-11e8-872a-fa881c9440e8.png)

**Comment by tattn** [comment]
Maybe fail to build SwipeTransition...

Please try to change `Swift Language Version` to swift 4.2 in the Pod project.
<img width="824" alt="screenshot" src="https://user-images.githubusercontent.com/8188636/45888410-eec18880-bdf8-11e8-97fa-e9668fa4d840.png">
