### ISSUE TITLE
iOS 11 bug with dismissScrollVC example 

### ISSUE THREAD

**Issue by mukyasa** [tattn/SwipeTransition#2]
The view controller gets stuck onScroll up down and it freezes, We have to close the app and restart it. Below I have attached screenshot

![bugscroll](https://user-images.githubusercontent.com/7480780/35607519-908fb72c-067a-11e8-9bbf-61601da68ce1.gif)

**Comment by tattn** [comment]
@mukyasa Thank you for the notice 👍 
I think that this issue was probably fixed in the latest version. Please try it!
