### ISSUE TITLE
Objective-c support

### ISSUE THREAD

**Issue by CavalcanteLeo** [tattn/SwipeTransition#4]
I'm trying to disable the pull to dismiss in some VCs, but can't find the property  `swipeToDismiss `

```objective-c
#import <SwipeTransition/SwipeTransition-Swift.h>

- (void)viewDidLoad {
    [super viewDidLoad];
    self.swipeToDismiss.isEnabled = NO;
    ...
}
```

All screens are working without any code typed. But i need to disable in some of them.

Is `swipeToDismiss` to disable the pull down, right?

<img width="692" alt="captura de tela 2018-03-27 as 23 52 35" src="https://user-images.githubusercontent.com/1735944/38006097-f42e8be4-3219-11e8-8d0e-6f25a8b0b593.png">

**Comment by tattn** [comment]
As of now, add the following header:

```objective-c
#import <SwipeTransition/SwipeTransition-Swift.h>
#import <AutoSwipeToDismiss/AutoSwipeToDismiss.h>
```

I'm considering better way to use easier!

**Comment by CavalcanteLeo** [comment]
Yep, that is it.
But as I've installed via cocoapods, I needed this headers:

```objective-c
#import <SwipeTransitionAutoSwipeToDismiss/AutoSwipeToDismiss.h>
```
